<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Merchandising\Services;

use DTS\eBaySDK\Merchandising\Types\GetRelatedCategoryItemsRequest;
use DTS\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse;
use GuzzleHttp\Promise\PromiseInterface;
use DTS\eBaySDK\Merchandising\Types\GetMostWatchedItemsRequest;
use DTS\eBaySDK\Merchandising\Types\GetTopSellingProductsRequest;
use DTS\eBaySDK\Merchandising\Types\MerchandisingServiceProductResponse;
use DTS\eBaySDK\Merchandising\Types\GetDealsRequest;
use DTS\eBaySDK\Merchandising\Types\GetSimilarItemsRequest;
use DTS\eBaySDK\Merchandising\Types\GetVersionRequest;
use DTS\eBaySDK\Merchandising\Types\GetVersionResponse;
class MerchandisingService extends MerchandisingBaseService
{
    const API_VERSION = '1.5.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param GetRelatedCategoryItemsRequest $request
     * @return MerchandisingServiceItemResponse
     */
    public function getRelatedCategoryItems(GetRelatedCategoryItemsRequest $request)
    {
        return $this->getRelatedCategoryItemsAsync($request)->wait();
    }

    /**
     * @param GetRelatedCategoryItemsRequest $request
     * @return PromiseInterface
     */
    public function getRelatedCategoryItemsAsync(GetRelatedCategoryItemsRequest $request)
    {
        return $this->callOperationAsync(
            'getRelatedCategoryItems',
            $request,
            '\DTS\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse'
        );
    }

    /**
     * @param GetMostWatchedItemsRequest $request
     * @return MerchandisingServiceItemResponse
     */
    public function getMostWatchedItems(GetMostWatchedItemsRequest $request)
    {
        return $this->getMostWatchedItemsAsync($request)->wait();
    }

    /**
     * @param GetMostWatchedItemsRequest $request
     * @return PromiseInterface
     */
    public function getMostWatchedItemsAsync(GetMostWatchedItemsRequest $request)
    {
        return $this->callOperationAsync(
            'getMostWatchedItems',
            $request,
            '\DTS\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse'
        );
    }

    /**
     * @param GetTopSellingProductsRequest $request
     * @return MerchandisingServiceProductResponse
     */
    public function getTopSellingProducts(GetTopSellingProductsRequest $request)
    {
        return $this->getTopSellingProductsAsync($request)->wait();
    }

    /**
     * @param GetTopSellingProductsRequest $request
     * @return PromiseInterface
     */
    public function getTopSellingProductsAsync(GetTopSellingProductsRequest $request)
    {
        return $this->callOperationAsync(
            'getTopSellingProducts',
            $request,
            '\DTS\eBaySDK\Merchandising\Types\MerchandisingServiceProductResponse'
        );
    }

    /**
     * @param GetDealsRequest $request
     * @return MerchandisingServiceItemResponse
     */
    public function getDeals(GetDealsRequest $request)
    {
        return $this->getDealsAsync($request)->wait();
    }

    /**
     * @param GetDealsRequest $request
     * @return PromiseInterface
     */
    public function getDealsAsync(GetDealsRequest $request)
    {
        return $this->callOperationAsync(
            'getDeals',
            $request,
            '\DTS\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse'
        );
    }

    /**
     * @param GetSimilarItemsRequest $request
     * @return MerchandisingServiceItemResponse
     */
    public function getSimilarItems(GetSimilarItemsRequest $request)
    {
        return $this->getSimilarItemsAsync($request)->wait();
    }

    /**
     * @param GetSimilarItemsRequest $request
     * @return PromiseInterface
     */
    public function getSimilarItemsAsync(GetSimilarItemsRequest $request)
    {
        return $this->callOperationAsync(
            'getSimilarItems',
            $request,
            '\DTS\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse'
        );
    }

    /**
     * @param GetVersionRequest $request
     * @return GetVersionResponse
     */
    public function getVersion(GetVersionRequest $request)
    {
        return $this->getVersionAsync($request)->wait();
    }

    /**
     * @param GetVersionRequest $request
     * @return PromiseInterface
     */
    public function getVersionAsync(GetVersionRequest $request)
    {
        return $this->callOperationAsync(
            'getVersion',
            $request,
            '\DTS\eBaySDK\Merchandising\Types\GetVersionResponse'
        );
    }
}
