<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Order\Types;

use DTS\eBaySDK\Order\Enums\LineItemPaymentStatusEnum;
use DTS\eBaySDK\Order\Enums\LineItemStatusEnum;
use DTS\eBaySDK\Types\BaseType;

/**
 *
 * @property Image $image
 * @property string $itemId
 * @property string $lineItemId
 * @property LineItemPaymentStatusEnum $lineItemPaymentStatus
 * @property LineItemStatusEnum $lineItemStatus
 * @property Amount $netPrice
 * @property integer $quantity
 * @property Seller $seller
 * @property ShippingDetail $shippingDetail
 * @property string $title
 */
class LineItem extends BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static array $propertyTypes = [
        'image'                 => [
            'type'        => 'DTS\eBaySDK\Order\Types\Image',
            'repeatable'  => false,
            'attribute'   => false,
            'elementName' => 'image'
        ],
        'itemId'                => [
            'type'        => 'string',
            'repeatable'  => false,
            'attribute'   => false,
            'elementName' => 'itemId'
        ],
        'lineItemId'            => [
            'type'        => 'string',
            'repeatable'  => false,
            'attribute'   => false,
            'elementName' => 'lineItemId'
        ],
        'lineItemPaymentStatus' => [
            'type'        => 'string',
            'repeatable'  => false,
            'attribute'   => false,
            'elementName' => 'lineItemPaymentStatus'
        ],
        'lineItemStatus'        => [
            'type'        => 'string',
            'repeatable'  => false,
            'attribute'   => false,
            'elementName' => 'lineItemStatus'
        ],
        'netPrice'              => [
            'type'        => 'DTS\eBaySDK\Order\Types\Amount',
            'repeatable'  => false,
            'attribute'   => false,
            'elementName' => 'netPrice'
        ],
        'quantity'              => [
            'type'        => 'integer',
            'repeatable'  => false,
            'attribute'   => false,
            'elementName' => 'quantity'
        ],
        'seller'                => [
            'type'        => 'DTS\eBaySDK\Order\Types\Seller',
            'repeatable'  => false,
            'attribute'   => false,
            'elementName' => 'seller'
        ],
        'shippingDetail'        => [
            'type'        => 'DTS\eBaySDK\Order\Types\ShippingDetail',
            'repeatable'  => false,
            'attribute'   => false,
            'elementName' => 'shippingDetail'
        ],
        'title'                 => [
            'type'        => 'string',
            'repeatable'  => false,
            'attribute'   => false,
            'elementName' => 'title'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
