<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\Compliance\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\Compliance\Types\GetListingViolationsSummaryRestRequest;

class GetListingViolationsSummaryRestRequestTest extends TestCase
{
    private GetListingViolationsSummaryRestRequest $obj;

    protected function setUp(): void
    {
        $this->obj = new GetListingViolationsSummaryRestRequest();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Compliance\Types\GetListingViolationsSummaryRestRequest', $this->obj);
    }

    public function testExtendsBaseType(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Types\BaseType', $this->obj);
    }
}
