<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Compliance\Services;

use DTS\eBaySDK\Compliance\Types\GetListingViolationsSummaryRestRequest;
use DTS\eBaySDK\Compliance\Types\GetListingViolationsSummaryRestResponse;
use GuzzleHttp\Promise\PromiseInterface;
use DTS\eBaySDK\Compliance\Types\GetListingViolationsRestRequest;
use DTS\eBaySDK\Compliance\Types\GetListingViolationsRestResponse;

class ComplianceService extends ComplianceBaseService
{
    const API_VERSION = 'v1';

    /**
     * @property array $operations Associative array of operations provided by the service.
     */
    protected static $operations = [
        'GetListingViolationsSummary' => [
            'method'        => 'GET',
            'resource'      => 'listing_violation_summary',
            'responseClass' => '\DTS\eBaySDK\Compliance\Types\GetListingViolationsSummaryRestResponse',
            'params'        => [
                'compliance_type' => [
                    'valid' => ['string']
                ]
            ]
        ],
        'GetListingViolations'        => [
            'method'        => 'GET',
            'resource'      => 'listing_violation',
            'responseClass' => '\DTS\eBaySDK\Compliance\Types\GetListingViolationsRestResponse',
            'params'        => [
                'limit'           => [
                    'valid' => ['integer']
                ],
                'listing_id'      => [
                    'valid' => ['string']
                ],
                'offset'          => [
                    'valid' => ['integer']
                ],
                'compliance_type' => [
                    'valid' => ['string']
                ]
            ]
        ]
    ];

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param GetListingViolationsSummaryRestRequest $request
     * @return GetListingViolationsSummaryRestResponse
     */
    public function getListingViolationsSummary(GetListingViolationsSummaryRestRequest $request)
    {
        return $this->getListingViolationsSummaryAsync($request)->wait();
    }

    /**
     * @param GetListingViolationsSummaryRestRequest $request
     * @return PromiseInterface
     */
    public function getListingViolationsSummaryAsync(GetListingViolationsSummaryRestRequest $request)
    {
        return $this->callOperationAsync('GetListingViolationsSummary', $request);
    }

    /**
     * @param GetListingViolationsRestRequest $request
     * @return GetListingViolationsRestResponse
     */
    public function getListingViolations(GetListingViolationsRestRequest $request)
    {
        return $this->getListingViolationsAsync($request)->wait();
    }

    /**
     * @param GetListingViolationsRestRequest $request
     * @return PromiseInterface
     */
    public function getListingViolationsAsync(GetListingViolationsRestRequest $request)
    {
        return $this->callOperationAsync('GetListingViolations', $request);
    }
}
