<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Catalog\Enums;

class ReferenceType
{
    public const C_INVENTORY_ITEM = 'INVENTORY_ITEM';
    public const C_LISTING = 'LISTING';
    public const C_LISTING_DRAFT = 'LISTING_DRAFT';
}
