<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\ProductMetadata\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkResponse;

class GetProductSearchValuesBulkResponseTest extends TestCase
{
    private GetProductSearchValuesBulkResponse $obj;

    protected function setUp(): void
    {
        $this->obj = new GetProductSearchValuesBulkResponse();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkResponse', $this->obj);
    }

    public function testExtendsGetProductSearchValuesResponse(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\ProductMetadata\Types\GetProductSearchValuesResponse', $this->obj);
    }
}
