<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\ProductMetadata\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\ProductMetadata\Types\ProductMetadataResponse;

class ProductMetadataResponseTest extends TestCase
{
    private ProductMetadataResponse $obj;

    protected function setUp(): void
    {
        $this->obj = new ProductMetadataResponse();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\ProductMetadata\Types\ProductMetadataResponse', $this->obj);
    }

    public function testExtendsBaseResponse(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\ProductMetadata\Types\BaseResponse', $this->obj);
    }
}
