<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\ProductMetadata\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\ProductMetadata\Types\TypeSpecificInformation;

class TypeSpecificInformationTest extends TestCase
{
    private TypeSpecificInformation $obj;

    protected function setUp(): void
    {
        $this->obj = new TypeSpecificInformation();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\ProductMetadata\Types\TypeSpecificInformation', $this->obj);
    }

    public function testExtendsBaseType(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Types\BaseType', $this->obj);
    }
}
