<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\BusinessPoliciesManagement\Enums;

class ProfileType
{
    public const C_PAYMENT = 'PAYMENT';
    public const C_RETURN_POLICY = 'RETURN_POLICY';
    public const C_SHIPPING = 'SHIPPING';
    public const C_SHIPPING_DISCOUNT = 'SHIPPING_DISCOUNT';
    public const C_SHIPPING_EXCLUSION = 'SHIPPING_EXCLUSION';
    public const C_SHIPPING_RATE = 'SHIPPING_RATE';
}
