<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Account\Types;

use DTS\eBaySDK\Account\Enums\PaymentInstrumentBrandEnum;
use DTS\eBaySDK\Account\Enums\PaymentMethodTypeEnum;
use DTS\eBaySDK\Types\BaseType;

/**
 *
 * @property PaymentInstrumentBrandEnum[] $brands
 * @property PaymentMethodTypeEnum $paymentMethodType
 * @property RecipientAccountReference $recipientAccountReference
 */
class PaymentMethod extends BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static array $propertyTypes = [
        'brands'                    => [
            'type'        => 'string',
            'repeatable'  => true,
            'attribute'   => false,
            'elementName' => 'brands'
        ],
        'paymentMethodType'         => [
            'type'        => 'string',
            'repeatable'  => false,
            'attribute'   => false,
            'elementName' => 'paymentMethodType'
        ],
        'recipientAccountReference' => [
            'type'        => 'DTS\eBaySDK\Account\Types\RecipientAccountReference',
            'repeatable'  => false,
            'attribute'   => false,
            'elementName' => 'recipientAccountReference'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
