<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\HalfFinding\Enums;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\HalfFinding\Enums\SortOrder;

class SortOrderTest extends TestCase
{
    private SortOrder $obj;

    protected function setUp(): void
    {
        $this->obj = new SortOrder();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\HalfFinding\Enums\SortOrder', $this->obj);
    }
}
