<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\Shopping\Enums;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\Shopping\Enums\TradingRoleCodeType;

class TradingRoleCodeTypeTest extends TestCase
{
    private TradingRoleCodeType $obj;

    protected function setUp(): void
    {
        $this->obj = new TradingRoleCodeType();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Shopping\Enums\TradingRoleCodeType', $this->obj);
    }
}
