<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Inventory\Types;

use DTS\eBaySDK\Inventory\Enums\SoldOnEnum;
use DTS\eBaySDK\Inventory\Enums\MinimumAdvertisedPriceHandlingEnum;
use DTS\eBaySDK\Types\BaseType;
/**
 *
 * @property Amount $minimumAdvertisedPrice
 * @property SoldOnEnum $originallySoldForRetailPriceOn
 * @property Amount $originalRetailPrice
 * @property Amount $price
 * @property MinimumAdvertisedPriceHandlingEnum $pricingVisibility
 */
class PricingSummary extends BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static array $propertyTypes = [
        'minimumAdvertisedPrice' => [
            'type' => 'DTS\eBaySDK\Inventory\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'minimumAdvertisedPrice'
        ],
        'originallySoldForRetailPriceOn' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'originallySoldForRetailPriceOn'
        ],
        'originalRetailPrice' => [
            'type' => 'DTS\eBaySDK\Inventory\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'originalRetailPrice'
        ],
        'price' => [
            'type' => 'DTS\eBaySDK\Inventory\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'price'
        ],
        'pricingVisibility' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'pricingVisibility'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
