<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\RelatedItemsManagement\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\RelatedItemsManagement\Types\Bundle;

class BundleTest extends TestCase
{
    private Bundle $obj;

    protected function setUp(): void
    {
        $this->obj = new Bundle();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\RelatedItemsManagement\Types\Bundle', $this->obj);
    }

    public function testExtendsBaseType(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Types\BaseType', $this->obj);
    }
}
