<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\RelatedItemsManagement\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\RelatedItemsManagement\Types\UpdateBundlesRequest;

class UpdateBundlesRequestTest extends TestCase
{
    private UpdateBundlesRequest $obj;

    protected function setUp(): void
    {
        $this->obj = new UpdateBundlesRequest();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\RelatedItemsManagement\Types\UpdateBundlesRequest', $this->obj);
    }

    public function testExtendsBaseRequest(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\RelatedItemsManagement\Types\BaseRequest', $this->obj);
    }
}
