<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\FileTransfer\Services;

use DTS\eBaySDK\FileTransfer\Types\UploadFileRequest;
use DTS\eBaySDK\FileTransfer\Types\UploadFileResponse;
use GuzzleHttp\Promise\PromiseInterface;
use DTS\eBaySDK\FileTransfer\Types\DownloadFileRequest;
use DTS\eBaySDK\FileTransfer\Types\DownloadFileResponse;
class FileTransferService extends FileTransferBaseService
{
    const API_VERSION = '1.1.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param UploadFileRequest $request
     * @return UploadFileResponse
     */
    public function uploadFile(UploadFileRequest $request)
    {
        return $this->uploadFileAsync($request)->wait();
    }

    /**
     * @param UploadFileRequest $request
     * @return PromiseInterface
     */
    public function uploadFileAsync(UploadFileRequest $request)
    {
        return $this->callOperationAsync(
            'uploadFile',
            $request,
            '\DTS\eBaySDK\FileTransfer\Types\UploadFileResponse'
        );
    }

    /**
     * @param DownloadFileRequest $request
     * @return DownloadFileResponse
     */
    public function downloadFile(DownloadFileRequest $request)
    {
        return $this->downloadFileAsync($request)->wait();
    }

    /**
     * @param DownloadFileRequest $request
     * @return PromiseInterface
     */
    public function downloadFileAsync(DownloadFileRequest $request)
    {
        return $this->callOperationAsync(
            'downloadFile',
            $request,
            '\DTS\eBaySDK\FileTransfer\Types\DownloadFileResponse'
        );
    }
}
