<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Finding\Enums;

class OutputSelectorType
{
    public const C_ASPECT_HISTOGRAM      = 'AspectHistogram';
    public const C_CATEGORY_HISTOGRAM    = 'CategoryHistogram';
    public const C_CONDITION_HISTOGRAM   = 'ConditionHistogram';
    public const C_GALLERY_INFO          = 'GalleryInfo';
    public const C_PICTUREURL_LARGE      = 'PictureURLLarge';
    public const C_PICTUREURL_SUPER_SIZE = 'PictureURLSuperSize';
    public const C_SELLER_INFO           = 'SellerInfo';
    public const C_STORE_INFO            = 'StoreInfo';
    public const C_UNIT_PRICE_INFO       = 'UnitPriceInfo';
}
