<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\Marketing\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\Marketing\Types\FindCampaignByAdReferenceRestResponse;

class FindCampaignByAdReferenceRestResponseTest extends TestCase
{
    private FindCampaignByAdReferenceRestResponse $obj;

    protected function setUp(): void
    {
        $this->obj = new FindCampaignByAdReferenceRestResponse();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Marketing\Types\FindCampaignByAdReferenceRestResponse', $this->obj);
    }

    public function testExtendsCampaigns(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Marketing\Types\Campaigns', $this->obj);
    }
}
