<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Shopping\Enums;

class ListingTypeCodeType
{
    public const C_AD_TYPE            = 'AdType';
    public const C_AUCTION            = 'Auction';
    public const C_CHINESE            = 'Chinese';
    public const C_CUSTOM_CODE        = 'CustomCode';
    public const C_DUTCH              = 'Dutch';
    public const C_EXPRESS            = 'Express';
    public const C_FIXED_PRICE_ITEM   = 'FixedPriceItem';
    public const C_HALF               = 'Half';
    public const C_LEAD_GENERATION    = 'LeadGeneration';
    public const C_LIVE               = 'Live';
    public const C_PERSONAL_OFFER     = 'PersonalOffer';
    public const C_STORES_FIXED_PRICE = 'StoresFixedPrice';
    public const C_UNKNOWN            = 'Unknown';
}
