<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Shopping\Enums;

class ProductIDCodeType
{
    public const C_CATALOG_ITEM = 'CatalogItem';
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_EAN = 'EAN';
    public const C_ISBN = 'ISBN';
    public const C_KEYWORDS = 'Keywords';
    public const C_MPN = 'MPN';
    public const C_REFERENCE = 'Reference';
    public const C_UPC = 'UPC';
}
