<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Marketing\Enums;

class DataTypeEnum
{
    public const C_DATE    = 'DATE';
    public const C_DOUBLE  = 'DOUBLE';
    public const C_INTEGER = 'INTEGER';
    public const C_LONG    = 'LONG';
    public const C_STRING  = 'STRING';
}
