<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Marketing\Enums;

class InventoryCriterionEnum
{
    public const C_INVENTORY_ANY      = 'INVENTORY_ANY';
    public const C_INVENTORY_BY_RULE  = 'INVENTORY_BY_RULE';
    public const C_INVENTORY_BY_VALUE = 'INVENTORY_BY_VALUE';
}
