<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Marketing\Enums;

class PromotionStatusEnum
{
    public const C_DRAFT     = 'DRAFT';
    public const C_ENDED     = 'ENDED';
    public const C_INVALID   = 'INVALID';
    public const C_PAUSED    = 'PAUSED';
    public const C_RUNNING   = 'RUNNING';
    public const C_SCHEDULED = 'SCHEDULED';
}
