<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Browse\Enums;

class PriceDisplayConditionEnum
{
    public const C_ALWAYS_SHOW                  = 'ALWAYS_SHOW';
    public const C_ONLY_SHOW_WHEN_ADDED_IN_CART = 'ONLY_SHOW_WHEN_ADDED_IN_CART';
}
