<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Inventory\Enums;

class ConditionEnum
{
    public const C_FOR_PARTS_OR_NOT_WORKING = 'FOR_PARTS_OR_NOT_WORKING';
    public const C_LIKE_NEW                 = 'LIKE_NEW';
    public const C_MANUFACTURER_REFURBISHED = 'MANUFACTURER_REFURBISHED';
    public const C_NEW                      = 'NEW';
    public const C_NEW_OTHER                = 'NEW_OTHER';
    public const C_NEW_WITH_DEFECTS         = 'NEW_WITH_DEFECTS';
    public const C_SELLER_REFURBISHED       = 'SELLER_REFURBISHED';
    public const C_USED_ACCEPTABLE          = 'USED_ACCEPTABLE';
    public const C_USED_EXCELLENT           = 'USED_EXCELLENT';
    public const C_USED_GOOD                = 'USED_GOOD';
    public const C_USED_VERY_GOOD           = 'USED_VERY_GOOD';
}
