<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Inventory\Enums;

class DayOfWeekEnum
{
    public const C_FRIDAY    = 'FRIDAY';
    public const C_MONDAY    = 'MONDAY';
    public const C_SATURDAY  = 'SATURDAY';
    public const C_SUNDAY    = 'SUNDAY';
    public const C_THURSDAY  = 'THURSDAY';
    public const C_TUESDAY   = 'TUESDAY';
    public const C_WEDNESDAY = 'WEDNESDAY';
}
