<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Inventory\Enums;

class LengthUnitOfMeasureEnum
{
    public const C_CENTIMETER = 'CENTIMETER';
    public const C_FEET = 'FEET';
    public const C_INCH = 'INCH';
    public const C_METER = 'METER';
}
