<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Inventory\Enums;

class ListingStatusEnum
{
    public const C_ACTIVE       = 'ACTIVE';
    public const C_EBAY_ENDED   = 'EBAY_ENDED';
    public const C_ENDED        = 'ENDED';
    public const C_INACTIVE     = 'INACTIVE';
    public const C_NOT_LISTED   = 'NOT_LISTED';
    public const C_OUT_OF_STOCK = 'OUT_OF_STOCK';
}
