<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Inventory\Enums;

class WeightUnitOfMeasureEnum
{
    public const C_GRAM     = 'GRAM';
    public const C_KILOGRAM = 'KILOGRAM';
    public const C_OUNCE    = 'OUNCE';
    public const C_POUND    = 'POUND';
}
