<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\Feedback\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\Feedback\Types\BaseServiceResponse;

class BaseServiceResponseTest extends TestCase
{
    private BaseServiceResponse $obj;

    protected function setUp(): void
    {
        $this->obj = new BaseServiceResponse();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Feedback\Types\BaseServiceResponse', $this->obj);
    }

    public function testExtendsBaseType(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Types\BaseType', $this->obj);
    }
}
