<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\ResolutionCaseManagement\Enums;

class AppealReasonType
{
    public const C_DISAGREE_WITH_FINAL_DECISION = 'DISAGREE_WITH_FINAL_DECISION';
    public const C_NEW_INFORMATION              = 'NEW_INFORMATION';
    public const C_OTHER                        = 'OTHER';
}
