<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\ResolutionCaseManagement\Enums;

class CaseSortOrderType
{
    public const C_CASE_STATUS_ASCENDING    = 'CASE_STATUS_ASCENDING';
    public const C_CASE_STATUS_DESCENDING   = 'CASE_STATUS_DESCENDING';
    public const C_CREATION_DATE_ASCENDING  = 'CREATION_DATE_ASCENDING';
    public const C_CREATION_DATE_DESCENDING = 'CREATION_DATE_DESCENDING';
}
