<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\ResolutionCaseManagement\Enums;

class EBPINRCaseStatusType
{
    public const C_CASE_CLOSED_CS_RESPONDED                   = 'CASE_CLOSED_CS_RESPONDED';
    public const C_CLOSED                                     = 'CLOSED';
    public const C_CS_CLOSED                                  = 'CS_CLOSED';
    public const C_EXPIRED                                    = 'EXPIRED';
    public const C_MY_PAYMENT_DUE                             = 'MY_PAYMENT_DUE';
    public const C_MY_RESPONSE_DUE                            = 'MY_RESPONSE_DUE';
    public const C_OTHER                                      = 'OTHER';
    public const C_OTHER_PARTY_CONTACTED_CS_AWAITING_RESPONSE = 'OTHER_PARTY_CONTACTED_CS_AWAITING_RESPONSE';
    public const C_OTHER_PARTY_RESPONSE_DUE                   = 'OTHER_PARTY_RESPONSE_DUE';
    public const C_PAID                                       = 'PAID';
    public const C_YOU_CONTACTED_CS_ABOUT_CLOSED_CASE         = 'YOU_CONTACTED_CS_ABOUT_CLOSED_CASE';
    public const C_YOU_CONTACTED_CS_AWAITING_RESPONSE         = 'YOU_CONTACTED_CS_AWAITING_RESPONSE';
}
