<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Fulfillment\Enums;

class CancelRequestStateEnum
{
    public const C_COMPLETED = 'COMPLETED';
    public const C_REJECTED  = 'REJECTED';
    public const C_REQUESTED = 'REQUESTED';
}
