<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Fulfillment\Enums;

class OrderFulfillmentStatus
{
    public const C_FULFILLED   = 'FULFILLED';
    public const C_IN_PROGRESS = 'IN_PROGRESS';
    public const C_NOT_STARTED = 'NOT_STARTED';
}
