<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\ReturnManagement\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\ReturnManagement\Types\ProvideSellerInfoOptionType;

class ProvideSellerInfoOptionTypeTest extends TestCase
{
    private ProvideSellerInfoOptionType $obj;

    protected function setUp(): void
    {
        $this->obj = new ProvideSellerInfoOptionType();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\ReturnManagement\Types\ProvideSellerInfoOptionType', $this->obj);
    }

    public function testExtendsBaseActivityOptionType(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\ReturnManagement\Types\BaseActivityOptionType', $this->obj);
    }
}
