<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class BestOfferTypeCodeType
{
    public const C_BUYER_BEST_OFFER     = 'BuyerBestOffer';
    public const C_BUYER_COUNTER_OFFER  = 'BuyerCounterOffer';
    public const C_CUSTOM_CODE          = 'CustomCode';
    public const C_SELLER_COUNTER_OFFER = 'SellerCounterOffer';
}
