<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class BusinessRoleType
{
    public const C_FULL_MARKET_PLACE_PARTICIPANT = 'FullMarketPlaceParticipant';
    public const C_SHOPPER                       = 'Shopper';
}
