<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class DiscountNameCodeType
{
    public const C_COMBINED_ITEM_WEIGHT            = 'CombinedItemWeight';
    public const C_CUSTOM_CODE                     = 'CustomCode';
    public const C_EACH_ADDITIONAL_AMOUNT          = 'EachAdditionalAmount';
    public const C_EACH_ADDITIONAL_AMOUNT_OFF      = 'EachAdditionalAmountOff';
    public const C_EACH_ADDITIONAL_PERCENT_OFF     = 'EachAdditionalPercentOff';
    public const C_INDIVIDUAL_ITEM_WEIGHT          = 'IndividualItemWeight';
    public const C_MAXIMUM_SHIPPING_COST_PER_ORDER = 'MaximumShippingCostPerOrder';
    public const C_SHIPPING_COSTX_FOR_AMOUNTY      = 'ShippingCostXForAmountY';
    public const C_SHIPPING_COSTX_FOR_ITEM_COUNTN  = 'ShippingCostXForItemCountN';
    public const C_WEIGHT_OFF                      = 'WeightOff';
}
