<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class EBaySubscriptionTypeCodeType
{
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_E_BAY_STORE_ANCHOR = 'EBayStoreAnchor';
    public const C_E_BAY_STORE_BASIC = 'EBayStoreBasic';
    public const C_E_BAY_STORE_FEATURED = 'EBayStoreFeatured';
    public const C_FILE_EXCHANGE = 'FileExchange';
    public const C_LOCAL_MARKET_PREMIUM = 'LocalMarketPremium';
    public const C_LOCAL_MARKET_REGULAR = 'LocalMarketRegular';
    public const C_LOCAL_MARKET_SPECIALTY = 'LocalMarketSpecialty';
    public const C_PICTURE_MANAGER_LEVEL1 = 'PictureManagerLevel1';
    public const C_PICTURE_MANAGER_LEVEL2 = 'PictureManagerLevel2';
    public const C_PICTURE_MANAGER_LEVEL3 = 'PictureManagerLevel3';
    public const C_PICTURE_MANAGER_LEVEL4 = 'PictureManagerLevel4';
    public const C_PICTURE_MANAGER_LEVEL5 = 'PictureManagerLevel5';
    public const C_PICTURE_MANAGER_LEVEL6 = 'PictureManagerLevel6';
    public const C_PICTURE_MANAGER_LEVEL7 = 'PictureManagerLevel7';
    public const C_SELLER_ASSISTANT = 'SellerAssistant';
    public const C_SELLER_ASSISTANT_PRO = 'SellerAssistantPro';
    public const C_SELLER_REPORTS_BASIC = 'SellerReportsBasic';
    public const C_SELLER_REPORTS_PLUS = 'SellerReportsPlus';
    public const C_SELLING_MANAGER = 'SellingManager';
    public const C_SELLING_MANAGER_PRO = 'SellingManagerPro';
}
