<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class EndReasonCodeType
{
    public const C_CUSTOM_CODE         = 'CustomCode';
    public const C_INCORRECT           = 'Incorrect';
    public const C_LOST_OR_BROKEN      = 'LostOrBroken';
    public const C_NOT_AVAILABLE       = 'NotAvailable';
    public const C_OTHER_LISTING_ERROR = 'OtherListingError';
    public const C_SELL_TO_HIGH_BIDDER = 'SellToHighBidder';
    public const C_SOLD                = 'Sold';
}
