<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class FeedbackRatingStarCodeType
{
    public const C_BLUE               = 'Blue';
    public const C_CUSTOM_CODE        = 'CustomCode';
    public const C_GREEN              = 'Green';
    public const C_GREEN_SHOOTING     = 'GreenShooting';
    public const C_NONE               = 'None';
    public const C_PURPLE             = 'Purple';
    public const C_PURPLE_SHOOTING    = 'PurpleShooting';
    public const C_RED                = 'Red';
    public const C_RED_SHOOTING       = 'RedShooting';
    public const C_SILVER_SHOOTING    = 'SilverShooting';
    public const C_TURQUOISE          = 'Turquoise';
    public const C_TURQUOISE_SHOOTING = 'TurquoiseShooting';
    public const C_YELLOW             = 'Yellow';
    public const C_YELLOW_SHOOTING    = 'YellowShooting';
}
