<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class PayPalAccountLevelCodeType
{
    public const C_CUSTOM_CODE              = 'CustomCode';
    public const C_INTERNATIONAL_UNVERIFIED = 'InternationalUnverified';
    public const C_INTERNATIONAL_VERIFIED   = 'InternationalVerified';
    public const C_INVALID                  = 'Invalid';
    public const C_TRUSTED                  = 'Trusted';
    public const C_UNKNOWN                  = 'Unknown';
    public const C_UNVERIFIED               = 'Unverified';
    public const C_VERIFIED                 = 'Verified';
}
