<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class ShipmentDeliveryStatusCodeType
{
    public const C_CANCELED = 'Canceled';
    public const C_CREATED = 'Created';
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_DELIVERED = 'Delivered';
    public const C_DROPPED_OFF = 'DroppedOff';
    public const C_ERROR = 'Error';
    public const C_IN_TRANSIT = 'InTransit';
    public const C_LABEL_PRINTED = 'LabelPrinted';
    public const C_RETURNED = 'Returned';
    public const C_UNCONFIRMED = 'Unconfirmed';
    public const C_UNKNOWN = 'Unknown';
}
