<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class TaxTypeCodeType
{
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_SALES_TAX = 'SalesTax';
    public const C_WASTE_RECYCLING_FEE = 'WasteRecyclingFee';
}
