<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class TradingRoleCodeType
{
    public const C_BUYER = 'Buyer';
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_SELLER = 'Seller';
}
