<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class TransactionPlatformCodeType
{
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_EXPRESS = 'Express';
    public const C_E_BAY = 'eBay';
    public const C_HALF = 'Half';
    public const C_SHOPPING = 'Shopping';
    public const C_WORLD_OF_GOOD = 'WorldOfGood';
}
