<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class BestOfferStatusCodeType
{
    public const C_ACCEPTED                   = 'Accepted';
    public const C_ACTIVE                     = 'Active';
    public const C_ADMIN_ENDED                = 'AdminEnded';
    public const C_ALL                        = 'All';
    public const C_COUNTERED                  = 'Countered';
    public const C_CUSTOM_CODE                = 'CustomCode';
    public const C_DECLINED                   = 'Declined';
    public const C_EXPIRED                    = 'Expired';
    public const C_PENDING                    = 'Pending';
    public const C_PENDING_BUYER_CONFIRMATION = 'PendingBuyerConfirmation';
    public const C_PENDING_BUYER_PAYMENT      = 'PendingBuyerPayment';
    public const C_RETRACTED                  = 'Retracted';
}
