<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class BidGroupItemStatusCodeType
{
    public const C_CANCELLED    = 'Cancelled';
    public const C_CURRENT_BID  = 'CurrentBid';
    public const C_CUSTOM_CODE  = 'CustomCode';
    public const C_ENDED        = 'Ended';
    public const C_GROUP_CLOSED = 'GroupClosed';
    public const C_PENDING      = 'Pending';
    public const C_SKIPPED      = 'Skipped';
    public const C_WON          = 'Won';
}
