<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class BulkCatalogListerStatusCodeType
{
    public const C_ACTIVE      = 'Active';
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_ON_HOLD     = 'OnHold';
    public const C_ON_WATCH    = 'OnWatch';
    public const C_PREAPPROVED = 'Preapproved';
    public const C_SUSPENDED   = 'Suspended';
    public const C_WATCH_WARN  = 'WatchWarn';
}
