<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class CheckoutMethodCodeType
{
    public const C_CUSTOM_CODE          = 'CustomCode';
    public const C_OTHER                = 'Other';
    public const C_THIRD_PARTY_CHECKOUT = 'ThirdPartyCheckout';
}
