<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class DeviceTypeCodeType
{
    public const C_CLIENT_ALERTS = 'ClientAlerts';
    public const C_CUSTOM_CODE   = 'CustomCode';
    public const C_PLATFORM      = 'Platform';
    public const C_SMS           = 'SMS';
}
