<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class EndOfAuctionLogoTypeCodeType
{
    public const C_CUSTOMIZED            = 'Customized';
    public const C_CUSTOM_CODE           = 'CustomCode';
    public const C_NONE                  = 'None';
    public const C_STORE                 = 'Store';
    public const C_WINNING_BIDDER_NOTICE = 'WinningBidderNotice';
}
