<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class ErrorHandlingCodeType
{
    public const C_ALL_OR_NOTHING = 'AllOrNothing';
    public const C_BEST_EFFORT    = 'BestEffort';
    public const C_FAIL_ON_ERROR  = 'FailOnError';
    public const C_LEGACY         = 'Legacy';
}
