<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class ItemTypeCodeType
{
    public const C_AD_FORMAT = 'AdFormat';
    public const C_ALL_FIXED_PRICE_ITEM_TYPES = 'AllFixedPriceItemTypes';
    public const C_ALL_ITEMS = 'AllItems';
    public const C_ALL_ITEM_TYPES = 'AllItemTypes';
    public const C_AUCTION_ITEMS_ONLY = 'AuctionItemsOnly';
    public const C_CLASSIFIED_ITEMS_ONLY = 'ClassifiedItemsOnly';
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_EXCLUDE_STORE_INVENTORY = 'ExcludeStoreInventory';
    public const C_FIXED_PRICED_ITEM = 'FixedPricedItem';
    public const C_FIXED_PRICE_EXCLUDE_STORE_INVENTORY = 'FixedPriceExcludeStoreInventory';
    public const C_STORE_INVENTORY_ONLY = 'StoreInventoryOnly';
}
