<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class MarkUpMarkDownEventTypeCodeType
{
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_MARK_DOWN   = 'MarkDown';
    public const C_MARK_UP     = 'MarkUp';
}
