<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class MessageTypeCodeType
{
    public const C_ALL = 'All';
    public const C_ASK_SELLER_QUESTION = 'AskSellerQuestion';
    public const C_CLASSIFIEDS_BEST_OFFER = 'ClassifiedsBestOffer';
    public const C_CLASSIFIEDS_CONTACT_SELLER = 'ClassifiedsContactSeller';
    public const C_CONTACTE_BAY_MEMBER_VIA_ANONYMOUS_EMAIL = 'ContacteBayMemberViaAnonymousEmail';
    public const C_CONTACTE_BAY_MEMBER_VIA_COMMUNITY_LINK = 'ContacteBayMemberViaCommunityLink';
    public const C_CONTACT_EBAY_MEMBER = 'ContactEbayMember';
    public const C_CONTACT_MY_BIDDER = 'ContactMyBidder';
    public const C_CONTACT_TRANSACTION_PARTNER = 'ContactTransactionPartner';
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_RESPONSE_TOASQ_QUESTION = 'ResponseToASQQuestion';
    public const C_RESPONSE_TO_CONTACTE_BAY_MEMBER = 'ResponseToContacteBayMember';
}
