<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class NotificationEventTypeCodeType
{
    public const C_ACCOUNT_SUMMARY                            = 'AccountSummary';
    public const C_ACCOUNT_SUSPENDED                          = 'AccountSuspended';
    public const C_ADD_TO_BID_GROUP                           = 'AddToBidGroup';
    public const C_ADD_TO_WATCH_LIST                          = 'AddToWatchList';
    public const C_ASK_SELLER_QUESTION                        = 'AskSellerQuestion';
    public const C_AUCTION_CHECKOUT_COMPLETE                  = 'AuctionCheckoutComplete';
    public const C_BEST_OFFER                                 = 'BestOffer';
    public const C_BEST_OFFER_DECLINED                        = 'BestOfferDeclined';
    public const C_BEST_OFFER_PLACED                          = 'BestOfferPlaced';
    public const C_BID_ITEM_ENDING_SOON                       = 'BidItemEndingSoon';
    public const C_BID_PLACED                                 = 'BidPlaced';
    public const C_BID_RECEIVED                               = 'BidReceived';
    public const C_BULK_DATA_EXCHANGE_JOB_COMPLETED           = 'BulkDataExchangeJobCompleted';
    public const C_BUYER_CANCEL_REQUESTED                     = 'BuyerCancelRequested';
    public const C_BUYER_NO_SHOW                              = 'BuyerNoShow';
    public const C_BUYER_RESPONSE_DISPUTE                     = 'BuyerResponseDispute';
    public const C_CHECKOUT_BUYER_REQUESTS_TOTAL              = 'CheckoutBuyerRequestsTotal';
    public const C_COUNTER_OFFER_RECEIVED                     = 'CounterOfferReceived';
    public const C_CUSTOM_CODE                                = 'CustomCode';
    public const C_EBN_ORDER_CANCELED                         = 'EBNOrderCanceled';
    public const C_EBN_ORDER_PICKED_UP                        = 'EBNOrderPickedUp';
    public const C_EBP_APPEALED_CASE                          = 'EBPAppealedCase';
    public const C_EBP_CLOSED_APPEAL                          = 'EBPClosedAppeal';
    public const C_EBP_CLOSED_CASE                            = 'EBPClosedCase';
    public const C_EBP_ESCALATED_CASE                         = 'EBPEscalatedCase';
    public const C_EBP_MY_PAYMENT_DUE                         = 'EBPMyPaymentDue';
    public const C_EBP_MY_RESPONSE_DUE                        = 'EBPMyResponseDue';
    public const C_EBP_ON_HOLD_CASE                           = 'EBPOnHoldCase';
    public const C_EBP_OTHER_PARTY_RESPONSE_DUE               = 'EBPOtherPartyResponseDue';
    public const C_EBP_PAYMENT_DONE                           = 'EBPPaymentDone';
    public const C_EMAIL_ADDRESS_CHANGED                      = 'EmailAddressChanged';
    public const C_END_OF_AUCTION                             = 'EndOfAuction';
    public const C_FEEDBACK                                   = 'Feedback';
    public const C_FEEDBACK_LEFT                              = 'FeedbackLeft';
    public const C_FEEDBACK_RECEIVED                          = 'FeedbackReceived';
    public const C_FEEDBACK_STAR_CHANGED                      = 'FeedbackStarChanged';
    public const C_FIXED_PRICE_TRANSACTION                    = 'FixedPriceTransaction';
    public const C_INR_BUYER_CLOSED_DISPUTE                   = 'INRBuyerClosedDispute';
    public const C_INR_BUYER_OPENED_DISPUTE                   = 'INRBuyerOpenedDispute';
    public const C_INR_BUYER_RESPONDED_TO_DISPUTE             = 'INRBuyerRespondedToDispute';
    public const C_INR_SELLER_RESPONDED_TO_DISPUTE            = 'INRSellerRespondedToDispute';
    public const C_ITEMS_CANCELED                             = 'ItemsCanceled';
    public const C_ITEM_ADDED_TO_WATCH_LIST                   = 'ItemAddedToWatchList';
    public const C_ITEM_CLOSED                                = 'ItemClosed';
    public const C_ITEM_EXTENDED                              = 'ItemExtended';
    public const C_ITEM_LISTED                                = 'ItemListed';
    public const C_ITEM_LOST                                  = 'ItemLost';
    public const C_ITEM_MARKED_PAID                           = 'ItemMarkedPaid';
    public const C_ITEM_MARKED_SHIPPED                        = 'ItemMarkedShipped';
    public const C_ITEM_OUT_OF_STOCK                          = 'ItemOutOfStock';
    public const C_ITEM_READY_FOR_PICKUP                      = 'ItemReadyForPickup';
    public const C_ITEM_REMOVED_FROM_WATCH_LIST               = 'ItemRemovedFromWatchList';
    public const C_ITEM_REVISED                               = 'ItemRevised';
    public const C_ITEM_REVISED_ADD_CHARITY                   = 'ItemRevisedAddCharity';
    public const C_ITEM_SOLD                                  = 'ItemSold';
    public const C_ITEM_SUSPENDED                             = 'ItemSuspended';
    public const C_ITEM_UNSOLD                                = 'ItemUnsold';
    public const C_ITEM_WON                                   = 'ItemWon';
    public const C_M2M_MESSAGE_STATUS_CHANGE                  = 'M2MMessageStatusChange';
    public const C_MY_MESSAGESE_BAY_MESSAGE                   = 'MyMessageseBayMessage';
    public const C_MY_MESSAGESE_BAY_MESSAGE_HEADER            = 'MyMessageseBayMessageHeader';
    public const C_MY_MESSAGESM2M_MESSAGE                     = 'MyMessagesM2MMessage';
    public const C_MY_MESSAGESM2M_MESSAGE_HEADER              = 'MyMessagesM2MMessageHeader';
    public const C_MY_MESSAGES_HIGH_PRIORITY_MESSAGE          = 'MyMessagesHighPriorityMessage';
    public const C_MY_MESSAGES_HIGH_PRIORITY_MESSAGE_HEADER   = 'MyMessagesHighPriorityMessageHeader';
    public const C_NONE                                       = 'None';
    public const C_ORDER_INQUIRY_CLOSED                       = 'OrderInquiryClosed';
    public const C_ORDER_INQUIRY_ESCALATED_TO_CASE            = 'OrderInquiryEscalatedToCase';
    public const C_ORDER_INQUIRY_OPENED                       = 'OrderInquiryOpened';
    public const C_ORDER_INQUIRY_PROVIDE_SHIPMENT_INFORMATION = 'OrderInquiryProvideShipmentInformation';
    public const C_ORDER_INQUIRY_REMINDER_FOR_ESCALATION      = 'OrderInquiryReminderForEscalation';
    public const C_OUT_BID                                    = 'OutBid';
    public const C_PASSWORD_CHANGED                           = 'PasswordChanged';
    public const C_PASSWORD_HINT_CHANGED                      = 'PasswordHintChanged';
    public const C_PAYMENT_DETAIL_CHANGED                     = 'PaymentDetailChanged';
    public const C_PAYMENT_REMINDER                           = 'PaymentReminder';
    public const C_PLACE_OFFER                                = 'PlaceOffer';
    public const C_READY_FOR_PAYOUT                           = 'ReadyForPayout';
    public const C_READY_TO_SHIP                              = 'ReadyToShip';
    public const C_REFUND_FAILURE                             = 'RefundFailure';
    public const C_REFUND_SUCCESS                             = 'RefundSuccess';
    public const C_REMOVE_FROM_BID_GROUP                      = 'RemoveFromBidGroup';
    public const C_REMOVE_FROM_WATCH_LIST                     = 'RemoveFromWatchList';
    public const C_RETURN_CLOSED                              = 'ReturnClosed';
    public const C_RETURN_CREATED                             = 'ReturnCreated';
    public const C_RETURN_DELIVERED                           = 'ReturnDelivered';
    public const C_RETURN_ESCALATED                           = 'ReturnEscalated';
    public const C_RETURN_REFUND_OVERDUE                      = 'ReturnRefundOverdue';
    public const C_RETURN_SELLER_INFO_OVERDUE                 = 'ReturnSellerInfoOverdue';
    public const C_RETURN_SHIPPED                             = 'ReturnShipped';
    public const C_RETURN_WAITING_FOR_SELLER_INFO             = 'ReturnWaitingForSellerInfo';
    public const C_SECOND_CHANCE_OFFER                        = 'SecondChanceOffer';
    public const C_SELLER_CLOSED_DISPUTE                      = 'SellerClosedDispute';
    public const C_SELLER_OPENED_DISPUTE                      = 'SellerOpenedDispute';
    public const C_SELLER_RESPONDED_TO_DISPUTE                = 'SellerRespondedToDispute';
    public const C_SHOPPING_CART_ITEM_ENDING_SOON             = 'ShoppingCartItemEndingSoon';
    public const C_TOKEN_REVOCATION                           = 'TokenRevocation';
    public const C_UNMATCHED_PAYMENT_RECEIVED                 = 'UnmatchedPaymentReceived';
    public const C_USERID_CHANGED                             = 'UserIDChanged';
    public const C_WATCHED_ITEM_ENDING_SOON                   = 'WatchedItemEndingSoon';
    public const C_WEBNEXT_MOBILE_PHOTO_SYNC                  = 'WebnextMobilePhotoSync';
}
