<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class PeriodCodeType
{
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_DAYS_1      = 'Days_1';
    public const C_DAYS_180    = 'Days_180';
    public const C_DAYS_30     = 'Days_30';
    public const C_DAYS_360    = 'Days_360';
    public const C_DAYS_540    = 'Days_540';
}
