<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class PictureManagerDetailLevelCodeType
{
    public const C_CUSTOM_CODE         = 'CustomCode';
    public const C_RETURN_ALL          = 'ReturnAll';
    public const C_RETURN_PICTURE      = 'ReturnPicture';
    public const C_RETURN_SUBSCRIPTION = 'ReturnSubscription';
}
