<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class PictureManagerActionCodeType
{
    public const C_ADD         = 'Add';
    public const C_CHANGE      = 'Change';
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_DELETE      = 'Delete';
    public const C_MOVE        = 'Move';
    public const C_RENAME      = 'Rename';
}
