<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class PictureManagerSubscriptionLevelCodeType
{
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_FREE = 'Free';
    public const C_LEVEL1 = 'Level1';
    public const C_LEVEL2 = 'Level2';
    public const C_LEVEL3 = 'Level3';
    public const C_LEVEL4 = 'Level4';
}
