<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class PreferredLocationCodeType
{
    public const C_AVAILABLE_IN_COUNTRY_IMPLIED = 'AvailableInCountryImplied';
    public const C_BELGIUM_LISTING = 'BelgiumListing';
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_LISTED_IN_CURRENCY_IMPLIED = 'ListedInCurrencyImplied';
    public const C_LOCATED_IN_COUNTRY_IMPLIED = 'LocatedInCountryImplied';
    public const C_SITE_IMPLIED = 'SiteImplied';
}
