<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class QuestionTypeCodeType
{
    public const C_CUSTOMIZED_SUBJECT = 'CustomizedSubject';
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_GENERAL = 'General';
    public const C_MULTIPLE_ITEM_SHIPPING = 'MultipleItemShipping';
    public const C_NONE = 'None';
    public const C_PAYMENT = 'Payment';
    public const C_SHIPPING = 'Shipping';
}
