<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class SellingManagerSearchTypeCodeType
{
    public const C_BUYER_EMAIL     = 'BuyerEmail';
    public const C_BUYER_FULL_NAME = 'BuyerFullName';
    public const C_BUYER_USERID    = 'BuyerUserID';
    public const C_CUSTOM_CODE     = 'CustomCode';
    public const C_CUSTOM_LABEL    = 'CustomLabel';
    public const C_ITEMID          = 'ItemID';
    public const C_PRODUCTID       = 'ProductID';
    public const C_PRODUCT_NAME    = 'ProductName';
    public const C_SALE_RECORDID   = 'SaleRecordID';
    public const C_TITLE           = 'Title';
}
