<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class SellingManagerPaidStatusCodeType
{
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_PAID = 'Paid';
    public const C_PARTIALLY_PAID = 'PartiallyPaid';
    public const C_PENDING = 'Pending';
    public const C_REFUNDED = 'Refunded';
    public const C_UNPAID = 'Unpaid';
}
