<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class SellereBayPaymentProcessStatusCodeType
{
    public const C_ACCEPTEDUA = 'AcceptedUA';
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_E_BAY_PAYMENT_PROCESS_ENABLED = 'eBayPaymentProcessEnabled';
    public const C_MUST_ACCEPTUA = 'MustAcceptUA';
}
