<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class SellerDashboardAlertSeverityCodeType
{
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_INFORMATIONAL = 'Informational';
    public const C_STRONG_WARNING = 'StrongWarning';
    public const C_WARNING = 'Warning';
}
