<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class StoreCustomListingHeaderLinkCodeType
{
    public const C_ABOUT_ME_PAGE = 'AboutMePage';
    public const C_CUSTOM_CATEGORY = 'CustomCategory';
    public const C_CUSTOM_CODE = 'CustomCode';
    public const C_CUSTOM_PAGE = 'CustomPage';
    public const C_NONE = 'None';
}
