<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class SummaryFrequencyCodeType
{
    public const C_CUSTOM_CODE     = 'CustomCode';
    public const C_EVERY31_DAYS    = 'Every31Days';
    public const C_EVERY60_DAYS    = 'Every60Days';
    public const C_EVERY_FRIDAY    = 'EveryFriday';
    public const C_EVERY_MONDAY    = 'EveryMonday';
    public const C_EVERY_SATURDAY  = 'EverySaturday';
    public const C_EVERY_SUNDAY    = 'EverySunday';
    public const C_EVERY_THURSDAY  = 'EveryThursday';
    public const C_EVERY_TUESDAY   = 'EveryTuesday';
    public const C_EVERY_WEDNESDAY = 'EveryWednesday';
    public const C_MONTHLY_ON10TH  = 'MonthlyOn10th';
    public const C_MONTHLY_ON11TH  = 'MonthlyOn11th';
    public const C_MONTHLY_ON12TH  = 'MonthlyOn12th';
    public const C_MONTHLY_ON13TH  = 'MonthlyOn13th';
    public const C_MONTHLY_ON14TH  = 'MonthlyOn14th';
    public const C_MONTHLY_ON15TH  = 'MonthlyOn15th';
    public const C_MONTHLY_ON16TH  = 'MonthlyOn16th';
    public const C_MONTHLY_ON17TH  = 'MonthlyOn17th';
    public const C_MONTHLY_ON18TH  = 'MonthlyOn18th';
    public const C_MONTHLY_ON19TH  = 'MonthlyOn19th';
    public const C_MONTHLY_ON1ST   = 'MonthlyOn1st';
    public const C_MONTHLY_ON20TH  = 'MonthlyOn20th';
    public const C_MONTHLY_ON21ST  = 'MonthlyOn21st';
    public const C_MONTHLY_ON22ND  = 'MonthlyOn22nd';
    public const C_MONTHLY_ON23RD  = 'MonthlyOn23rd';
    public const C_MONTHLY_ON24TH  = 'MonthlyOn24th';
    public const C_MONTHLY_ON25TH  = 'MonthlyOn25th';
    public const C_MONTHLY_ON26TH  = 'MonthlyOn26th';
    public const C_MONTHLY_ON27TH  = 'MonthlyOn27th';
    public const C_MONTHLY_ON28TH  = 'MonthlyOn28th';
    public const C_MONTHLY_ON29TH  = 'MonthlyOn29th';
    public const C_MONTHLY_ON2ND   = 'MonthlyOn2nd';
    public const C_MONTHLY_ON30TH  = 'MonthlyOn30th';
    public const C_MONTHLY_ON31ST  = 'MonthlyOn31st';
    public const C_MONTHLY_ON3RD   = 'MonthlyOn3rd';
    public const C_MONTHLY_ON4TH   = 'MonthlyOn4th';
    public const C_MONTHLY_ON5TH   = 'MonthlyOn5th';
    public const C_MONTHLY_ON6TH   = 'MonthlyOn6th';
    public const C_MONTHLY_ON7TH   = 'MonthlyOn7th';
    public const C_MONTHLY_ON8TH   = 'MonthlyOn8th';
    public const C_MONTHLY_ON9TH   = 'MonthlyOn9th';
}
