<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class CancelStateEnum
{
    public const C_APPROVAL_PENDING       = 'APPROVAL_PENDING';
    public const C_CLOSED                 = 'CLOSED';
    public const C_CONFIRM_REFUND_PENDING = 'CONFIRM_REFUND_PENDING';
    public const C_INITIAL                = 'INITIAL';
    public const C_OTHER                  = 'OTHER';
    public const C_REFUND_INITIATED       = 'REFUND_INITIATED';
    public const C_REFUND_PENDING         = 'REFUND_PENDING';
}
