<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class EligibilityCheckTypeEnum
{
    public const C_ITEM_SELECTION             = 'ITEM_SELECTION';
    public const C_PRE_TRANSACTION            = 'PRE_TRANSACTION';
    public const C_REPLACEMENT_CREATION       = 'REPLACEMENT_CREATION';
    public const C_REPLACEMENT_ITEM_SELECTION = 'REPLACEMENT_ITEM_SELECTION';
    public const C_RETURN_CREATION            = 'RETURN_CREATION';
}
