<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class FileFormatEnum
{
    public const C_BMP = 'BMP';
    public const C_GIF = 'GIF';
    public const C_JPEG = 'JPEG';
    public const C_JPG = 'JPG';
    public const C_PNG = 'PNG';
    public const C_UNKNOWN = 'UNKNOWN';
}
