<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class FileStatusEnum
{
    public const C_CREATED = 'CREATED';
    public const C_DELETED = 'DELETED';
    public const C_PUBLISHED = 'PUBLISHED';
    public const C_UNKNOWN = 'UNKNOWN';
}
