<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class InquiryStateEnum
{
    public const C_AUTO_DISPOSE_MONEY_MOVEMENT_PENDING    = 'AUTO_DISPOSE_MONEY_MOVEMENT_PENDING';
    public const C_CLOSED                                 = 'CLOSED';
    public const C_CREATED                                = 'CREATED';
    public const C_FULL_REFUND_AGREED                     = 'FULL_REFUND_AGREED';
    public const C_INITIAL                                = 'INITIAL';
    public const C_ON_HOLD_FOR_UPLOAD                     = 'ON_HOLD_FOR_UPLOAD';
    public const C_OTHER                                  = 'OTHER';
    public const C_PARTIAL_REFUND_ACCEPTED                = 'PARTIAL_REFUND_ACCEPTED';
    public const C_PARTIAL_REFUND_OFFERED                 = 'PARTIAL_REFUND_OFFERED';
    public const C_PENDING_CREATED                        = 'PENDING_CREATED';
    public const C_SELLER_ECHECK_FULL_REFUND_INITIATED    = 'SELLER_ECHECK_FULL_REFUND_INITIATED';
    public const C_SELLER_ECHECK_PARTIAL_REFUND_INITIATED = 'SELLER_ECHECK_PARTIAL_REFUND_INITIATED';
    public const C_SELLER_ECHECK_REFUND_GRACE_EXPIRED     = 'SELLER_ECHECK_REFUND_GRACE_EXPIRED';
    public const C_SHIPPING_INFO_PROVIDED                 = 'SHIPPING_INFO_PROVIDED';
    public const C_TRACKING_PROVIDED                      = 'TRACKING_PROVIDED';
    public const C_VOLUNTARY_REFUND_PAYOUT_PENDING        = 'VOLUNTARY_REFUND_PAYOUT_PENDING';
}
