<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class LabelPrintStatusEnum
{
    public const C_EXPIRED   = 'EXPIRED';
    public const C_FAILED    = 'FAILED';
    public const C_PRINTED   = 'PRINTED';
    public const C_REQUESTED = 'REQUESTED';
    public const C_UNKNOWN   = 'UNKNOWN';
}
