<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class MoneyMovementTypeEnum
{
    public const C_AUTO_REFUND = 'AUTO_REFUND';
    public const C_BUYER_MASS_PAYOUT = 'BUYER_MASS_PAYOUT';
    public const C_BUYER_PAYOUT = 'BUYER_PAYOUT';
    public const C_BUYER_RECOUP = 'BUYER_RECOUP';
    public const C_CHARGE_BUYER_FOR_REPLACEMENT = 'CHARGE_BUYER_FOR_REPLACEMENT';
    public const C_CHARGE_BUYER_FOR_RETURN_SHIPPING = 'CHARGE_BUYER_FOR_RETURN_SHIPPING';
    public const C_INVOICE_SELLER_FOR_RETURN_SHIPPING = 'INVOICE_SELLER_FOR_RETURN_SHIPPING';
    public const C_NON_PAYPAL_FULL_REFUND = 'NON_PAYPAL_FULL_REFUND';
    public const C_NON_PAYPAL_PARTIAL_REFUND = 'NON_PAYPAL_PARTIAL_REFUND';
    public const C_PAYPAL_PARTIAL_REFUND = 'PAYPAL_PARTIAL_REFUND';
    public const C_PAYPAL_REFUND = 'PAYPAL_REFUND';
    public const C_REFUND_FVF_ITEM_COST = 'REFUND_FVF_ITEM_COST';
    public const C_REFUND_FVF_SHIPPING_COST = 'REFUND_FVF_SHIPPING_COST';
    public const C_REFUND_PROMOTED_LISTING_FEE = 'REFUND_PROMOTED_LISTING_FEE';
    public const C_SELLER_PAYOUT = 'SELLER_PAYOUT';
    public const C_SELLER_VOLUNTARY_REFUND = 'SELLER_VOLUNTARY_REFUND';
    public const C_STORE_CREDIT = 'STORE_CREDIT';
    public const C_UNKNOWN = 'UNKNOWN';
}
