<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class OrderTypeEnum
{
    public const C_EBAY_NOW        = 'EBAY_NOW';
    public const C_IN_STORE_PICKUP = 'IN_STORE_PICKUP';
    public const C_ONLINE          = 'ONLINE';
    public const C_OTHER           = 'OTHER';
}
