<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class ReturnCountFilterEnum
{
    public const C_ALL_OPEN             = 'ALL_OPEN';
    public const C_ALL_OPEN_REPLACEMENT = 'ALL_OPEN_REPLACEMENT';
    public const C_ALL_OPEN_RETURN      = 'ALL_OPEN_RETURN';
    public const C_CLOSED               = 'CLOSED';
    public const C_ITEM_DELIVERED       = 'ITEM_DELIVERED';
    public const C_ITEM_SHIPPED         = 'ITEM_SHIPPED';
    public const C_RETURN_STARTED       = 'RETURN_STARTED';
    public const C_UNKNOWN              = 'UNKNOWN';
}
