<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class ReturnStatusEnum
{
    public const C_CLOSED                         = 'CLOSED';
    public const C_ESCALATED                      = 'ESCALATED';
    public const C_ITEM_DELIVERED                 = 'ITEM_DELIVERED';
    public const C_ITEM_SHIPPED                   = 'ITEM_SHIPPED';
    public const C_LESS_THAN_A_FULL_REFUND_ISSUED = 'LESS_THAN_A_FULL_REFUND_ISSUED';
    public const C_PARTIAL_REFUND_DECLINED        = 'PARTIAL_REFUND_DECLINED';
    public const C_PARTIAL_REFUND_FAILED          = 'PARTIAL_REFUND_FAILED';
    public const C_PARTIAL_REFUND_INITIATED       = 'PARTIAL_REFUND_INITIATED';
    public const C_PARTIAL_REFUND_REQUESTED       = 'PARTIAL_REFUND_REQUESTED';
    public const C_READY_FOR_SHIPPING             = 'READY_FOR_SHIPPING';
    public const C_REPLACED                       = 'REPLACED';
    public const C_REPLACEMENT_CLOSED             = 'REPLACEMENT_CLOSED';
    public const C_REPLACEMENT_DELIVERED          = 'REPLACEMENT_DELIVERED';
    public const C_REPLACEMENT_LABEL_REQUESTED    = 'REPLACEMENT_LABEL_REQUESTED';
    public const C_REPLACEMENT_REQUESTED          = 'REPLACEMENT_REQUESTED';
    public const C_REPLACEMENT_SHIPPED            = 'REPLACEMENT_SHIPPED';
    public const C_REPLACEMENT_STARTED            = 'REPLACEMENT_STARTED';
    public const C_REPLACEMENT_WAITING_FOR_RMA    = 'REPLACEMENT_WAITING_FOR_RMA';
    public const C_RETURN_LABEL_REQUESTED         = 'RETURN_LABEL_REQUESTED';
    public const C_RETURN_REJECTED                = 'RETURN_REJECTED';
    public const C_RETURN_REQUESTED               = 'RETURN_REQUESTED';
    public const C_RETURN_REQUESTED_TIMEOUT       = 'RETURN_REQUESTED_TIMEOUT';
    public const C_UNKNOWN                        = 'UNKNOWN';
    public const C_WAITING_FOR_RETURN_LABEL       = 'WAITING_FOR_RETURN_LABEL';
    public const C_WAITING_FOR_RMA                = 'WAITING_FOR_RMA';
}
