<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class ReturnSortEnum
{
    public const C_ACTUAL_AMOUNT    = 'ACTUAL_AMOUNT';
    public const C_BUYER_LOGIN_NAME = 'BUYER_LOGIN_NAME';
    public const C_ESTIMATED_AMOUNT = 'ESTIMATED_AMOUNT';
    public const C_FILING_DATE      = 'FILING_DATE';
    public const C_REASON           = 'REASON';
    public const C_REFUND_DUE_DATE  = 'REFUND_DUE_DATE';
    public const C_RETURN_ID        = 'RETURN_ID';
    public const C_STATUS           = 'STATUS';
    public const C_UNKNOWN          = 'UNKNOWN';
}
