<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class TrackingStatusEnum
{
    public const C_CANCELLED  = 'CANCELLED';
    public const C_CREATED    = 'CREATED';
    public const C_DELIVERED  = 'DELIVERED';
    public const C_IN_TRANSIT = 'IN_TRANSIT';
    public const C_UNKNOWN    = 'UNKNOWN';
}
