<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\Inventory\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\Inventory\Types\CreateInventoryLocationRestRequest;

class CreateInventoryLocationRestRequestTest extends TestCase
{
    private CreateInventoryLocationRestRequest $obj;

    protected function setUp(): void
    {
        $this->obj = new CreateInventoryLocationRestRequest();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Inventory\Types\CreateInventoryLocationRestRequest', $this->obj);
    }

    public function testExtendsInventoryLocationFull(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Inventory\Types\InventoryLocationFull', $this->obj);
    }
}
