<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\Merchandising\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse;

class MerchandisingServiceItemResponseTest extends TestCase
{
    private MerchandisingServiceItemResponse $obj;

    protected function setUp(): void
    {
        $this->obj = new MerchandisingServiceItemResponse();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Merchandising\Types\MerchandisingServiceItemResponse', $this->obj);
    }

    public function testExtendsBaseMerchandisingServiceResponse(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Merchandising\Types\BaseMerchandisingServiceResponse', $this->obj);
    }
}
