<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Order\Enums;

class PurchaseOrderStatusEnum
{
    public const C_CANCELLED = 'CANCELLED';
    public const C_DELIVERED = 'DELIVERED';
    public const C_FULFILLMENT_IN_PROGRESS = 'FULFILLMENT_IN_PROGRESS';
    public const C_PENDING = 'PENDING';
}
