<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\Fulfillment\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\Fulfillment\Types\ShippingStep;

class ShippingStepTest extends TestCase
{
    private ShippingStep $obj;

    protected function setUp(): void
    {
        $this->obj = new ShippingStep();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Fulfillment\Types\ShippingStep', $this->obj);
    }

    public function testExtendsBaseType(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Types\BaseType', $this->obj);
    }
}
