<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\HalfFinding\Enums;

class ItemFilterType
{
    public const C_CONDITION          = 'Condition';
    public const C_EXCLUDE_SELLER     = 'ExcludeSeller';
    public const C_FEEDBACK_SCORE_MIN = 'FeedbackScoreMin';
    public const C_LISTING_TYPE       = 'ListingType';
    public const C_MAX_PRICE          = 'MaxPrice';
    public const C_SELLER             = 'Seller';
    public const C_SHIPPING_SERVICE   = 'ShippingService';
}
