<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\HalfFinding\Enums;

class RentalDurationType
{
    public const C_DAYS125 = 'Days125';
    public const C_DAYS30 = 'Days30';
    public const C_DAYS45 = 'Days45';
    public const C_DAYS60 = 'Days60';
    public const C_DAYS90 = 'Days90';
}
