<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\HalfFinding\Enums;

class SortOrder
{
    public const C_DECREASING = 'DECREASING';
    public const C_INCREASING = 'INCREASING';
}
