<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\HalfFinding\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\HalfFinding\Types\RentalAmount;

class RentalAmountTest extends TestCase
{
    private RentalAmount $obj;

    protected function setUp(): void
    {
        $this->obj = new RentalAmount();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\HalfFinding\Types\RentalAmount', $this->obj);
    }

    public function testExtendsDoubleType(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Types\DoubleType', $this->obj);
    }
}
