<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\PostOrder\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\PostOrder\Types\GetReturnEstimateRestResponse;

class GetReturnEstimateRestResponseTest extends TestCase
{
    private GetReturnEstimateRestResponse $obj;

    protected function setUp(): void
    {
        $this->obj = new GetReturnEstimateRestResponse();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\PostOrder\Types\GetReturnEstimateRestResponse', $this->obj);
    }

    public function testExtendsGetEstimateResponse(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\PostOrder\Types\GetEstimateResponse', $this->obj);
    }
}
