<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\PostOrder\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\PostOrder\Types\UpdateCustomListRestRequest;

class UpdateCustomListRestRequestTest extends TestCase
{
    private UpdateCustomListRestRequest $obj;

    protected function setUp(): void
    {
        $this->obj = new UpdateCustomListRestRequest();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\PostOrder\Types\UpdateCustomListRestRequest', $this->obj);
    }

    public function testExtendsModifyCustomListRequest(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\PostOrder\Types\ModifyCustomListRequest', $this->obj);
    }
}
