<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\PostOrder\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\PostOrder\Types\UploadReturnDraftFileRestRequest;

class UploadReturnDraftFileRestRequestTest extends TestCase
{
    private UploadReturnDraftFileRestRequest $obj;

    protected function setUp(): void
    {
        $this->obj = new UploadReturnDraftFileRestRequest();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\PostOrder\Types\UploadReturnDraftFileRestRequest', $this->obj);
    }

    public function testExtendsUploadFileRequest(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\PostOrder\Types\UploadFileRequest', $this->obj);
    }
}
