<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\PostOrder\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\PostOrder\Types\VoidShippingLabelRestRequest;

class VoidShippingLabelRestRequestTest extends TestCase
{
    private VoidShippingLabelRestRequest $obj;

    protected function setUp(): void
    {
        $this->obj = new VoidShippingLabelRestRequest();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\PostOrder\Types\VoidShippingLabelRestRequest', $this->obj);
    }

    public function testExtendsVoidLabelRequest(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\PostOrder\Types\VoidLabelRequest', $this->obj);
    }
}
