<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\Account\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\Account\Types\GetReturnPoliciesByMarketplaceRestResponse;

class GetReturnPoliciesByMarketplaceRestResponseTest extends TestCase
{
    private GetReturnPoliciesByMarketplaceRestResponse $obj;

    protected function setUp(): void
    {
        $this->obj = new GetReturnPoliciesByMarketplaceRestResponse();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Account\Types\GetReturnPoliciesByMarketplaceRestResponse', $this->obj);
    }

    public function testExtendsReturnPolicyResponse(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Account\Types\ReturnPolicyResponse', $this->obj);
    }
}
