<?php

/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Test\Account\Types;

use PHPUnit\Framework\TestCase;
use DTS\eBaySDK\Account\Types\OptOutOfProgramRestRequest;

class OptOutOfProgramRestRequestTest extends TestCase
{
    private OptOutOfProgramRestRequest $obj;

    protected function setUp(): void
    {
        $this->obj = new OptOutOfProgramRestRequest();
    }

    public function testCanBeCreated(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Account\Types\OptOutOfProgramRestRequest', $this->obj);
    }

    public function testExtendsProgram(): void
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Account\Types\Program', $this->obj);
    }
}
