<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Types;

use DTS\eBaySDK\Types\BaseType;
/**
 *
 * @property MerchantDataRequestHeaderType $Header
 * @property AddFixedPriceItemRequestType[] $AddFixedPriceItemRequest
 * @property AddItemRequestType[] $AddItemRequest
 * @property EndFixedPriceItemRequestType[] $EndFixedPriceItemRequest
 * @property EndItemRequestType[] $EndItemRequest
 * @property OrderAckRequestType[] $OrderAckRequest
 * @property RelistFixedPriceItemRequestType[] $RelistFixedPriceItemRequest
 * @property RelistItemRequestType[] $RelistItemRequest
 * @property ReviseFixedPriceItemRequestType[] $ReviseFixedPriceItemRequest
 * @property ReviseInventoryStatusRequestType[] $ReviseInventoryStatusRequest
 * @property ReviseItemRequestType[] $ReviseItemRequest
 * @property SetShipmentTrackingInfoRequestType[] $SetShipmentTrackingInfoRequest
 * @property UploadSiteHostedPicturesRequestType[] $UploadSiteHostedPicturesRequest
 * @property VerifyAddFixedPriceItemRequestType[] $VerifyAddFixedPriceItemRequest
 * @property VerifyAddItemRequestType[] $VerifyAddItemRequest
 */
class BulkDataExchangeRequestsType extends BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static array $propertyTypes = [
        'Header' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\MerchantDataRequestHeaderType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Header'
        ],
        'AddFixedPriceItemRequest' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\AddFixedPriceItemRequestType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'AddFixedPriceItemRequest'
        ],
        'AddItemRequest' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\AddItemRequestType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'AddItemRequest'
        ],
        'EndFixedPriceItemRequest' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EndFixedPriceItemRequestType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'EndFixedPriceItemRequest'
        ],
        'EndItemRequest' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\EndItemRequestType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'EndItemRequest'
        ],
        'OrderAckRequest' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\OrderAckRequestType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'OrderAckRequest'
        ],
        'RelistFixedPriceItemRequest' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\RelistFixedPriceItemRequestType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'RelistFixedPriceItemRequest'
        ],
        'RelistItemRequest' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\RelistItemRequestType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'RelistItemRequest'
        ],
        'ReviseFixedPriceItemRequest' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ReviseFixedPriceItemRequestType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ReviseFixedPriceItemRequest'
        ],
        'ReviseInventoryStatusRequest' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ReviseInventoryStatusRequestType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ReviseInventoryStatusRequest'
        ],
        'ReviseItemRequest' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\ReviseItemRequestType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ReviseItemRequest'
        ],
        'SetShipmentTrackingInfoRequest' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\SetShipmentTrackingInfoRequestType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'SetShipmentTrackingInfoRequest'
        ],
        'UploadSiteHostedPicturesRequest' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\UploadSiteHostedPicturesRequestType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'UploadSiteHostedPicturesRequest'
        ],
        'VerifyAddFixedPriceItemRequest' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\VerifyAddFixedPriceItemRequestType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'VerifyAddFixedPriceItemRequest'
        ],
        'VerifyAddItemRequest' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\VerifyAddItemRequestType',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'VerifyAddItemRequest'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        if (!array_key_exists(__CLASS__, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[__CLASS__] = 'BulkDataExchangeRequests';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
