<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\BulkDataExchange\Enums;

class IncludeShippingAddressType
{
    public const C_ALWAYS            = 'Always';
    public const C_CHECKOUT_COMPLETE = 'CheckoutComplete';
}
